version: "3"

services:
  postgres:
    image: postgres:14.1
    container_name: hyperback-postgres-container
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - api-hyperback-network
    env_file: ./config/.env

  redis:
    image: redis:6.2.6
    container_name: hyperback-container
    volumes:
      - redisdata:/data
    networks:
      - api-hyperback-network
    env_file: ./config/.env

  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: "hypeback-api:latest"
    restart: "unless-stopped"
    stop_grace_period: "5s"
    volumes:
      - ./src:/usr/src/app
      - django-static:/var/www/django/static
    depends_on:
      - postgres
      - redis
    networks:
      - api-hyperback-network
      - api-hyperback-proxy-network
    env_file: ./config/.env
    container_name: hyperback-container
    ports:
      - "8000:8000"

  production:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: "hypeback-api:latest"
    restart: "unless-stopped"
    stop_grace_period: "5s"
    volumes:
      - ./src:/usr/src/app
      - django-static:/var/www/django/static
    depends_on:
      - postgres
      - redis
    networks:
      - api-hyperback-network
      - api-hyperback-proxy-network
    env_file: ./config/.env
    container_name: hyperback-production-container
    ports:
      - "8000:8000"

networks:
  api-hyperback-proxy-network:

  api-hyperback-network:

volumes:
  pgdata:
  redisdata:
  django-static:
  django-media:
  django-locale:
