[tool.pycodestyle]
statistics = true

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true

[tool.isort]
profile = "black"
combine_as_imports = true
force_grid_wrap = 0
force_sort_within_sections = true
include_trailing_comma = true
known_django= "django"
known_first_party = "api,consumer"
multi_line_output = 3
sections = "FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
skip_glob = [
    "**migrations**"
]
use_parentheses = true

[tool.pytest.ini_options]
python_files = "test*.py"
norecursedirs = ".* build dist CVS _darcs {arch} *.egg *.egg-info venv docs .git appdir .tox"
console_output_style = "progress"
testpaths = [
    "consumer",
]
addopts = "--ds=api.settings --durations=5 --cov-report=term-missing --cov=."
