name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy-production:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Run Deploy
        uses: appleboy/ssh-action@master
        env:
          BEAT_SERVICE: ${{ secrets.BEAT_SERVICE }}
          WORKER_SERVICE: ${{ secrets.WORKER_SERVICE }}
          APPLICATION_SERVICE: ${{ secrets.APPLICATION_SERVICE }}
          PROJECT_FOLDER: ${{ secrets.PROJECT_FOLDER }}
        with:
          host: ${{ secrets.STAGING_SSH_HOST }}
          username: ${{ secrets.STAGING_SSH_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          envs: BEAT_SERVICE,WORKER_SERVICE,APPLICATION_SERVICE,PROJECT_FOLDER
          script: |
            eval $(ssh-agent)
            ssh-add github
            systemctl stop $BEAT_SERVICE
            systemctl stop $WORKER_SERVICE
            systemctl stop $APPLICATION_SERVICE
            cd $PROJECT_FOLDER && git pull
            systemctl start $APPLICATION_SERVICE
            systemctl start $WORKER_SERVICE
            systemctl start $BEAT_SERVICE
